[package]
name = "crypto"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
efficient-sm2 = "0.1.5"
clap = "3.0.0-beta.2"
log = "0.4.14"
hex = "0.4.3"
